include(":data")
include(":di")
include(":domain")
include(
    ":presentation:app",
    ":presentation:models",
    ":presentation:navigation",
    ":presentation:features:champions",
    ":presentation:features:championDetail"
)
